"""Provenance helpers for the RECAST synthetic-materials corpus.

Two responsibilities:

  1. Resolve a `--ckpt` argument (path-style, possibly absolute or relative)
     to a canonical `model_version` string and look up its training-dataset
     version_id in the checkpoint registry.
  2. Stamp `model_version`, `screen_id`, and `dataset_version` onto an
     `atoms.info` dict so downstream extxyz writers carry full provenance.

The checkpoint registry is generated by
`scripts/build_checkpoint_registry.py` and lives at
`data/checkpoint_registry.json`. It is loaded lazily at first use.

Stamping is idempotent: callers that re-stamp the same atoms simply update
the same keys.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = ROOT / "data/checkpoint_registry.json"
ED_CHECKPOINTS = Path("/data/rkumar/code/py/ed/checkpoints")


@lru_cache(maxsize=1)
def _registry() -> list[dict[str, Any]]:
    if not REGISTRY_PATH.exists():
        return []
    return json.loads(REGISTRY_PATH.read_text())


@lru_cache(maxsize=1)
def _registry_by_name() -> dict[str, dict[str, Any]]:
    return {e["model_version"]: e for e in _registry()}


def resolve_model_version(ckpt_arg: str | Path | None) -> str | None:
    """Resolve a checkpoint argument to its canonical model_version.

    A `model_version` is the directory name that contains the `.pt` files
    (e.g. `ckpt_autolabel_v1_binrho_k7`) — the same canonical key used in
    the checkpoint registry.

    Accepts:
      - Absolute path to a `.pt` file → use parent dir name.
      - Absolute path to a checkpoint directory → use its name.
      - Relative path under ED_CHECKPOINTS → resolve and use dir name.
      - Bare name (e.g. `recast-base-k7`) → returned as-is.

    Returns None if input is None.
    """
    if ckpt_arg is None:
        return None
    p = Path(str(ckpt_arg))

    # If it's an existing path, use parent or self.
    if p.exists():
        if p.is_file():
            return p.parent.name
        if p.is_dir():
            return p.name

    # Relative-to-ED-checkpoints resolution.
    candidate = ED_CHECKPOINTS / p
    if candidate.exists():
        if candidate.is_file():
            return candidate.parent.name
        if candidate.is_dir():
            return candidate.name

    # Fallback: take the first non-`.pt` path component.
    parts = [part for part in p.parts if not part.endswith(".pt")]
    if parts:
        return parts[-1]
    return None


def lookup_dataset_version(model_version: str | None) -> str | None:
    """Return the registry's training_dataset_version_id, or None."""
    if not model_version:
        return None
    entry = _registry_by_name().get(model_version)
    if not entry:
        return None
    return entry.get("training_dataset_version_id")


def lookup_entry(model_version: str | None) -> dict[str, Any] | None:
    if not model_version:
        return None
    return _registry_by_name().get(model_version)


def stamp_provenance(
    atoms,
    model_version: str | None,
    screen_id: str | None,
    dataset_version: str | None = None,
    extra: dict[str, Any] | None = None,
) -> None:
    """Add provenance keys to atoms.info (in place).

    Keys stamped:
      - `model_version`: e.g. `recast-base-k7`.
      - `screen_id`: e.g. `20260605_134500_1234` from screen_registry.
      - `dataset_version`: e.g. `d15_binrho_k7` (looked up if not given).
      - any keys provided in `extra`.

    Skips fields whose value is None.
    """
    if model_version is not None:
        atoms.info["model_version"] = model_version
        if dataset_version is None:
            dataset_version = lookup_dataset_version(model_version)
    if screen_id is not None:
        atoms.info["screen_id"] = screen_id
    if dataset_version is not None:
        atoms.info["dataset_version"] = dataset_version
    if extra:
        for k, v in extra.items():
            if v is not None:
                atoms.info[k] = v


def write_checkpoint_metadata(
    checkpoint_dir: str | Path,
    *,
    training_dataset: str | None = None,
    training_dataset_csv: str | None = None,
    hyperparams: dict[str, Any] | None = None,
    git_sha: str | None = None,
    training_run_id: str | None = None,
    extra: dict[str, Any] | None = None,
) -> Path:
    """Emit `<checkpoint_dir>/metadata.json` so future builds of the registry
    pick up an explicit (non-inferred) provenance entry for this checkpoint.

    The schema mirrors `CheckpointEntry` in build_checkpoint_registry.py.
    """
    cdir = Path(checkpoint_dir)
    cdir.mkdir(parents=True, exist_ok=True)

    payload: dict[str, Any] = {
        "model_version": cdir.name,
        "checkpoint_path": str(cdir),
        "kind": "recast",
        "training_dataset": training_dataset,
        "training_dataset_csv": training_dataset_csv,
        "hyperparams": hyperparams or {},
        "git_sha": git_sha,
        "training_run_id": training_run_id,
        "source": "explicit_metadata",
        "inferred": False,
    }
    if extra:
        payload.update(extra)

    out = cdir / "metadata.json"
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return out
