#!/usr/bin/env python3
"""fig_dpo_logprob_dist.png  (Claim 4.4 — the aggressive-fine-tune boundary).

Two overlaid histograms: per-token log-probability of held-out base-distribution structures
under the BASE model vs the aggressively fine-tuned (DPO/IPO) model. Mark the uniform-vocab
baseline (-log 16000 = -9.70). Fine-tuned mass below uniform ⇒ off the base support.

Held-out base structures = fresh samples GENERATED by the base model itself (so they are
base-distribution and correctly encoded for both models, since the DPO model was fine-tuned
from this base and shares its tokenizer). We then score the same token sequences under each.

NEEDS CHECKPOINTS (not in this data-light repo). Set:
    CUES_BASE_CKPT  -> base model dir (e.g. the production checkpoint dir)
    CUES_DPO_CKPT   -> the fine-tuned DPO checkpoint .pt
and run with the same env as score.py (HF_TOKEN; one venv). Output -> figures/.

CAVEAT (provenance): the paper's figure uses the IPO-novelty checkpoint; that checkpoint and
its training data were lost with the original box. This script was run with base = production
and DPO = a stand-in (`checkpoints_dpo_ox`). Because the held-out set is the base model's own
generations, the base distribution piles up near 0 (the base is near-certain on its own
samples); the qualitative off-support result (DPO mass ≈ -15, below the -9.7 uniform line)
holds regardless. For a moderate base distribution, use a real held-out set in the base
model's encoding instead of self-generations.
"""
import sys, os, json, math, random
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
for p in ["lemat/code/py/ed", "lemat/code/py/dielectric", "lemat/code/py/lemat-genbench/src"]:
    fp = os.path.join(ROOT, p)
    if os.path.isdir(fp):
        sys.path.insert(0, fp)
for p in ["/home/ubuntu/code/py/ed", "/home/ubuntu/code/py/dielectric",
          "/home/ubuntu/packages/lemat-genbench/src"]:
    if os.path.isdir(p):
        sys.path.append(p)
import numpy as np
import torch
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from eval.screening import load_model
from ed_model import EdGPT
from ed_translate import translate_batch

BASE_DIR = os.environ.get("CUES_BASE_CKPT", "/home/ubuntu/code/py/ed/checkpoints/ckpt_ed_enclight_6_18")
DPO_PT   = os.environ.get("CUES_DPO_CKPT", "/home/ubuntu/code/py/ed/checkpoints/checkpoints_dpo_ox/dpo_ckpt_final.pt")
DIST     = os.path.join(ROOT, "lemat/data/distributions/an_lh.dist.json")
FIG      = os.path.join(ROOT, "figures"); os.makedirs(FIG, exist_ok=True)
RESULTS  = os.path.join(ROOT, "results"); os.makedirs(RESULTS, exist_ok=True)
DEVICE   = os.environ.get("CUES_DEVICE", "cuda")
N_STRUCT, GEN_BS, VOCAB = 250, 32, 16000
UNIFORM_LP = -math.log(VOCAB)            # -9.70 per token


def log(m): print(m, flush=True)


def load_dpo(path, device):
    ck = torch.load(path, map_location="cpu", weights_only=False)
    cfg = ck["config"]
    sd = {k.removeprefix("_orig_mod."): v for k, v in ck["model"].items()}
    if not any("q_norm" in k for k in sd) and getattr(cfg, "qk_norm", False):
        cfg.qk_norm = False                                          # same fix load_model uses
    m = EdGPT(cfg)
    m.load_state_dict(sd, strict=False)
    return m.to(device).eval()


def tok_target(sp, text, max_len=1024):
    tgt = sp.encode(text, out_type=int)[:max_len - 1]
    return [sp.bos_id()] + tgt, tgt + [sp.eos_id()]                  # dec_in, labels (== dpo_data.py)


@torch.no_grad()
def per_token_lp(model, items, device):
    out = []
    for i in range(0, len(items), GEN_BS):
        chunk = items[i:i + GEN_BS]
        S = max(len(s) for s, _, _ in chunk); T = max(len(d) for _, d, _ in chunk)
        src = torch.zeros(len(chunk), S, dtype=torch.long)
        din = torch.zeros(len(chunk), T, dtype=torch.long)
        lab = torch.full((len(chunk), T), -100, dtype=torch.long)
        for j, (s, d, l) in enumerate(chunk):
            src[j, :len(s)] = torch.tensor(s); din[j, :len(d)] = torch.tensor(d)
            lab[j, :len(l)] = torch.tensor(l)
        src, din, lab = src.to(device), din.to(device), lab.to(device)
        logits, _ = model(din, src, src_mask=(src != 0), tgt_mask=(din != 0))
        lp = F.log_softmax(logits.float(), dim=-1)
        tok = lp.gather(-1, lab.clamp(min=0).unsqueeze(-1)).squeeze(-1)
        m = (lab != -100).float()
        out.extend(((tok * m).sum(-1) / m.sum(-1).clamp(min=1)).cpu().tolist())
    return out


def main():
    log("loading base + dpo ...")
    base, sp = load_model(BASE_DIR, DEVICE)
    dpo = load_dpo(DPO_PT, DEVICE)

    tuples = json.load(open(DIST))
    rng = random.Random(0)
    keys = [(d["elements"], int(d["natoms"])) for d in tuples]
    w = [int(d["count"]) for d in tuples]
    prompts = [f"{e} | {n} | " for e, n in rng.choices(keys, weights=w, k=N_STRUCT)]

    log(f"generating {N_STRUCT} held-out structures from the base model ...")
    targets = []
    for i in range(0, len(prompts), GEN_BS):
        targets.extend(translate_batch(base, sp, prompts[i:i + GEN_BS], DEVICE, 512, 10))
        log(f"  {min(i+GEN_BS, len(prompts))}/{len(prompts)}")

    items = []
    for src, tgt in zip(prompts, targets):
        if not tgt or not tgt.strip():
            continue
        din, lab = tok_target(sp, tgt)
        if len(lab) >= 2:
            items.append((sp.encode(src, out_type=int)[:1024], din, lab))

    base_lp = per_token_lp(base, items, DEVICE)
    dpo_lp = per_token_lp(dpo, items, DEVICE)
    bm, dm = float(np.mean(base_lp)), float(np.mean(dpo_lp))
    log(f"mean per-token log-prob:  base {bm:.2f}  dpo {dm:.2f}  uniform {UNIFORM_LP:.2f}")

    fig, ax = plt.subplots(figsize=(6.2, 3.8))
    lo = math.floor(min(min(base_lp), min(dpo_lp)) - 1)
    hi = math.ceil(max(max(base_lp), max(dpo_lp)) + 1)
    bins = np.linspace(lo, hi, 46)
    ax.hist(base_lp, bins=bins, alpha=0.6, color="#2b6cb0", label=f"base (production)  μ={bm:.1f}")
    ax.hist(dpo_lp, bins=bins, alpha=0.6, color="#dd6b20", label=f"fine-tuned (DPO)  μ={dm:.1f}")
    ax.axvline(UNIFORM_LP, color="k", ls="--", lw=1.4, label=f"uniform vocab ({UNIFORM_LP:.1f})")
    ax.set_xlabel("per-token log-probability of held-out base structures")
    ax.set_ylabel("count")
    ax.set_title("Claim 4.4: aggressive fine-tuning moves off the base support")
    ax.legend(fontsize=8.5)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "fig_dpo_logprob_dist.png"), dpi=160)
    plt.close(fig)
    json.dump({"n": len(items), "base_mean": bm, "dpo_mean": dm, "uniform": UNIFORM_LP,
               "base_lp": base_lp, "dpo_lp": dpo_lp, "base_ckpt": BASE_DIR, "dpo_ckpt": DPO_PT},
              open(os.path.join(RESULTS, "dpo_logprob_fig.json"), "w"))
    log("wrote figures/fig_dpo_logprob_dist.png + results/dpo_logprob_fig.json")


if __name__ == "__main__":
    main()
